baseURL: https://alisabetx.com/
enableRobotsTXT: true
canonifyURLs: true
relativeURLs: false
title: 62235103

defaultContentLanguageInSubdir: true
defaultContentLanguage: fa
languageCode: fa
languageName: فارسی

theme: PaperMod

pagination:
  pagerSize: 10

disqusShortname: alisabetx

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
    - Sitemap

permalinks:
  posts: /posts/:year/:month/:slug/
  pages: /:slug/

markup:
  highlight:
    lineNos: true
    style: github-dark
    tabWidth: 4
    codeFences: false
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

params:
  env: production
  analytics:
    google:
      SiteVerificationTag: "G-CNTN4F9XNJ"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"
