title: Ali Sabet
description: .NET developer with a heart for AI
keywords: [Blog, Ali Sabet]

DateFormat: "2006-01-02"
defaultTheme: dark
disableThemeToggle: false

rssFullContent: true
ShowReadingTime: true
ShowShareButtons: true
ShareButtons: ["linkedin", "twitter", "whatsapp", "telegram"]
ShowPostNavLinks: false
ShowBreadCrumbs: false
ShowCodeCopyButtons: true
ShowWordCount: false
ShowRssButtonInSectionTermList: true
UseHugoToc: false
ShowToc: true
TocOpen: false
disableSpecial1stPost: true
disableScrollToTop: false
comments: true
hidemeta: false
hideSummary: false
draft: false
disableHLJS: true
disableShare: false
searchHidden: true
mainSections: ["posts"]

buildDrafts: false
buildFuture: false
buildExpired: false

homeInfoParams:
  Title: Ali Sabet
  Content: Softeare Engineer, .NET developer, AI lover!

socialIcons:
  - name: linkedin
    url: https://linkedin.com/in/alisabetx/
  - name: github
    url: https://github.com/alisabetx/
  - name: x
    url: https://x.com/alisabetx/
  - name: youtube
    url: http://youtube.com/@alixsabet/
  - name: letterboxd
    url: https://letterboxd.com/alisabetx/
  - name: goodreads
    url: https://goodreads.com/alisabetx/
  - name: rss
    url: https://alisabetx.com/en/index.xml

cover:
  hidden: true
  hiddenInList: true
  hiddenInSingle: true

editPost:
  URL: "https://github.com/alisabetx/blog/tree/main/content"
  Text: "Suggest Changes"
  appendFilePath: true

fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  limit: 10
  keys: ["title", "permalink", "summary", "content"]